apiVersion: v1
kind: PersistentVolume   
metadata:
  name: db-pv    
spec:
  capacity:
    storage: 400Mi          
  accessModes:
  - ReadWriteOnce         
  storageClassName: db-snipeit-storage
  
