apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: dbclaim0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: db-snipeit-storage
  resources:
    requests:
      storage: 2Gi
status: {}
