apiVersion: v1
kind: PersistentVolume   
metadata:
  name: db-pv	      
spec:
  capacity:
    storage: 8Gi          
  accessModes:
  - ReadWriteOnce         
  hostPath:              
    path: /tmp
