apiVersion: v1
kind: PersistentVolume   
metadata:
  name: db	      
spec:
  capacity:
    storage: 1Gi          
  accessModes:
  - ReadWriteOnce         
  storageClassName: db-snipeit-storage
  hostPath:              
    path: /tmp
