apiVersion: v1
kind: PersistentVolume   
metadata:
  name: snipeit-pv      
spec:
  capacity:
    storage: 6Gi          
  accessModes:
  - ReadWriteOnce         
  storageClassName: db-snipeit-storage
 
