apiVersion: apps/v1
kind: Deployment
metadata:
  name: snipe-it
  labels:
    app: snipe-it
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snipe-it
  template:
    metadata:
      labels:
        app: snipe-it
    spec:
      containers:
        - name: snipe-it-container
          image: 172.23.8.1:9500/snipe-it:v0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: snipe-it
